export const FOR_LIVE_PAGE_MESSAGES = "LIVEPAGEMESSAGES";
export const FOR_CONTROL_TOWER_PAGE_MESSAGES = "CONTROLTOWERPAGEMESSAGES";
export const FOR_ROUTES_PALN_PAGE_MESSAGES = "FORROUTESPALNPAGEMESSAGES";
export const FOR_NAV_BAR_PAGE_MESSAGES = "NAVBARPAGEMESSAGES";
export const SEQUENCE_ORDERS = "Sequence Orders";
export const BALANCED_ALLOCATIONS = "Balanced Allocation";
export const TIME_AND_FUEL_OPTIMIZATION = "Time And Fuel Optimization";
export const MULTI_TRIP = "Multi Trip";
export const INPUT_TYPE_RADIO = "radio";
export const INPUT_TYPE_CHECKBOX = "checkbox";
export const ORDER_DELIVERED = 4
export const ALL_ORDERS = 1111001111
export const UNASSIGNED_ORDERS = 111101111
export const ORDERS_IN_PRODUCTION = 'OrdersInProdcution'
export const ORDERS_READYFORPICKUP = 'Ready For Pick Up'
export const DELIVERY_TRIPS = 'DeliveryTrips'
export const ORDER_STATUS_DELIVERED = "DELIVERED"
export const ORDER_STATUS_PENDING = "PLACED"
export const ORDER_STATUS_CANCELLED = "CANCELED"
export const ORDER_STATUS_CONFIRMED = "CONFIRMED"
export const ORDER_STATUS_READY_FOR_PICKUP = "READY_FOR_PICK_UP"
export const ORDER_STATUS_ON_HOLD = "ON HOLD"
export const ORDER_STATUS_ON_HOLD_BY_SALES = "ON HOLD BY SALES"
export const ORDER_STATUS_SHIPPED = "SHIPPED"
export const TRIP_STATUS_WAITING = 'Assigned'
export const TRIP_STATUS_STARTED = 'STARTED'
export const TRIP_STATUS_NOTSTARTED = 'ASSIGNED'
export const TRIP_STATUS_COMPLETED = 'CLOSED'
export const TRIP_STATUS_PARTIALLY_CLOSED = 'PARTIALLY_CLOSED'
export const TRIP_STATUS_CLOSED = 'CLOSED'
export const col1 = 'col-md-1 col-xs-1 col-sm-1 col-lg-1'
export const col2 = 'col-md-2 col-xs-2 col-sm-2 col-lg-2'
export const col3 = 'col-md-3 col-xs-3 col-sm-3 col-lg-3'
export const col5 = 'col-md-5 col-xs-5 col-sm-5 col-lg-5'
export const col4 = 'col-md-4 col-xs-4 col-sm-4 col-lg-4'
export const col6 = 'col-md-6 col-xs-6 col-sm-6 col-lg-6'
export const col7 = 'col-md-7 col-xs-7 col-sm-7 col-lg-7'
export const col8 = 'col-md-8 col-xs-8 col-sm-8 col-lg-8'
export const col9 = 'col-md-9 col-xs-9 col-sm-9 col-lg-9'
export const col10 = 'col-md-10 col-xs-10 col-sm-10 col-lg-10'
export const col11 = 'col-md-11 col-xs-11 col-sm-11 col-lg-11'
export const col12 = 'col-md-12 col-xs-12 col-sm-12 col-lg-12'
export const col_md_auto = 'col-md-auto'
export const col_lg_auto = 'col-lg-auto'
export const col_sm_auto = 'col-sm-auto'
export const col_xs_auto = 'col-xs-auto'
export const PAYMENT_TYPE_CASH_ON_DELIVERY = 'CASH_ON_DELIVERY'
export const PAYMENT_TYPE_POS = 'POINT_OF_SALE'
export const PAYMENT_TYPE_MOYASAR_CREDIT_CARD = 'CREDIT_CARD'
export const PAYMENT_TYPE_MADA_CREDIT_CARD = 'MADA'
export const PAYMENT_TYPE_CARD_ON_DELIVERY = 'CARD_ON_DELIVERY'
export const WALLET = 'WALLET'
export const STC_PAY = 'STC_PAY'
export const DELIVERY_TYPE_ANYTIME = 3
export const DELIVERY_TYPE_MORNING = 1
export const DELIVERY_TYPE_EVENING = 2
export const LANG_AR='ar'
export const LANG_EN='en'